// !!! This is a file automatically generated by hipify!!!
#include "hip/hip_runtime.h"
// Copyright (c) 2009-2022, NVIDIA CORPORATION.  All rights reserved.
//
// NVIDIA CORPORATION and its licensors retain all intellectual property
// and proprietary rights in and to this software, related documentation
// and any modifications thereto.  Any use, reproduction, disclosure or
// distribution of this software and related documentation without an express
// license agreement from NVIDIA CORPORATION is strictly prohibited.

#include "../../framework_hip.h"
#include "../../hipraster/impl/Constants.hpp"
#include "../../hipraster/impl/PrivateDefs.hpp"
#include "../../hipraster/impl/RasterImpl.hpp"
#include <hip/hip_runtime.h>
#include <iostream>
#include <unistd.h>

using namespace CR;
using std::max;
using std::min;

//------------------------------------------------------------------------
// Kernel prototypes and variables.

// AMD RDNA3 workaround: 2 unified kernels instead of 4 separate ones.
// Dispatching 3+ different kernel functions crashes on RDNA3/ROCm 6.4.
void setupKernel(const CRParams* p, int stage);   // stage 0=triSetup, 1=binRaster
void rasterKernel(const CRParams* p, int stage);  // stage 0=coarseRaster, 1=fineRaster

//------------------------------------------------------------------------

RasterImpl::RasterImpl(void)
    : m_renderModeFlags(0), m_deferredClear(false), m_clearColor(0),
      m_vertexPtr(NULL), m_indexPtr(NULL), m_numVertices(0), m_numTriangles(0),
      m_bufferSizesReported(0),

      m_d_crParams(NULL), m_stream2(NULL), m_drawCount(0),
      m_graphExec(NULL), m_graphNumTriangles(0), m_graphNumImages(0), // unused but kept in header

      m_numImages(0), m_bufferSizePixels(0, 0), m_bufferSizeVp(0, 0),
      m_sizePixels(0, 0), m_sizeVp(0, 0), m_offsetPixels(0, 0),
      m_sizeBins(0, 0), m_numBins(0), m_sizeTiles(0, 0), m_numTiles(0),

      m_numSMs(1), m_numCoarseBlocksPerSM(1), m_numFineBlocksPerSM(1),
      m_numFineWarpsPerBlock(1),

      m_maxSubtris(1), m_maxBinSegs(1), m_maxTileSegs(1) {
  // Query relevant device attributes.

  int currentDevice = 0;
  NVDR_CHECK_CUDA_ERROR(hipGetDevice(&currentDevice));
  NVDR_CHECK_CUDA_ERROR(hipDeviceGetAttribute(
      &m_numSMs, hipDeviceAttributeMultiprocessorCount, currentDevice));
  // Query attributes from rasterKernel (handles both coarse and fine stages).
  hipFuncAttributes attr;
  NVDR_CHECK_CUDA_ERROR(hipFuncGetAttributes(
      &attr, reinterpret_cast<const void *>(rasterKernel)));
  m_numFineWarpsPerBlock = min(attr.maxThreadsPerBlock / 32, CR_FINE_MAX_WARPS);
  // Static shared memory in kernel -- pass 0 for dynamic smem in occupancy queries.
  NVDR_CHECK_CUDA_ERROR(hipOccupancyMaxActiveBlocksPerMultiprocessor(
      &m_numCoarseBlocksPerSM, (void *)rasterKernel, 32 * CR_COARSE_WARPS,
      0));
  NVDR_CHECK_CUDA_ERROR(hipOccupancyMaxActiveBlocksPerMultiprocessor(
      &m_numFineBlocksPerSM, (void *)rasterKernel,
      32 * m_numFineWarpsPerBlock, 0));

  // Setup functions.

  NVDR_CHECK_CUDA_ERROR(hipFuncSetCacheConfig((void *)setupKernel,
                                              hipFuncCachePreferShared));
  NVDR_CHECK_CUDA_ERROR(hipFuncSetCacheConfig((void *)rasterKernel,
                                              hipFuncCachePreferShared));

  // AMD multi-dispatch workaround: create second stream for coarse+fine raster.
  // Dispatching 3+ different kernels on the same stream crashes on RDNA3/ROCm 6.4.
  NVDR_CHECK_CUDA_ERROR(hipStreamCreate(&m_stream2));

  int maxSmemPerBlock = 0;
  NVDR_CHECK_CUDA_ERROR(hipDeviceGetAttribute(
      &maxSmemPerBlock, hipDeviceAttributeMaxSharedMemoryPerBlock, currentDevice));
  std::cerr << "[RasterImpl ctor @" << (void*)this << "] dev=" << currentDevice
            << " maxSmemPerBlock=" << maxSmemPerBlock
            << " SMs=" << m_numSMs
            << " coarseBlocks=" << m_numCoarseBlocksPerSM
            << " fineBlocks=" << m_numFineBlocksPerSM
            << " fineWarps=" << m_numFineWarpsPerBlock
            << " regsPerThread=" << attr.numRegs
            << " smemPerBlock=" << attr.sharedSizeBytes
            << " d_crParams=" << m_d_crParams
            << std::endl;
}

//------------------------------------------------------------------------

RasterImpl::~RasterImpl(void) {
  if (m_graphExec) {
    hipGraphExecDestroy(m_graphExec);
    m_graphExec = NULL;
  }
  if (m_stream2) {
    hipStreamDestroy(m_stream2);
    m_stream2 = NULL;
  }
  if (m_d_crParams) {
    hipFree(m_d_crParams);
    m_d_crParams = NULL;
  }
}

//------------------------------------------------------------------------

void RasterImpl::setBufferSize(Vec3i size) {
  // Internal buffer width and height must be divisible by tile size.
  int w = (size.x + CR_TILE_SIZE - 1) & (-CR_TILE_SIZE);
  int h = (size.y + CR_TILE_SIZE - 1) & (-CR_TILE_SIZE);

  m_bufferSizePixels = Vec2i(w, h);
  m_bufferSizeVp = Vec2i(size.x, size.y);
  m_numImages = size.z;

  m_colorBuffer.reset(w * h * size.z * sizeof(U32));
  m_depthBuffer.reset(w * h * size.z * sizeof(U32));
}

//------------------------------------------------------------------------

void RasterImpl::setViewport(Vec2i size, Vec2i offset) {
  // Offset must be divisible by tile size.
  NVDR_CHECK((offset.x & (CR_TILE_SIZE - 1)) == 0 &&
                 (offset.y & (CR_TILE_SIZE - 1)) == 0,
             "invalid viewport offset");

  // Round internal viewport size to multiples of tile size.
  int w = (size.x + CR_TILE_SIZE - 1) & (-CR_TILE_SIZE);
  int h = (size.y + CR_TILE_SIZE - 1) & (-CR_TILE_SIZE);

  m_sizePixels = Vec2i(w, h);
  m_offsetPixels = offset;
  m_sizeVp = Vec2i(size.x, size.y);
  m_sizeTiles.x = m_sizePixels.x >> CR_TILE_LOG2;
  m_sizeTiles.y = m_sizePixels.y >> CR_TILE_LOG2;
  m_numTiles = m_sizeTiles.x * m_sizeTiles.y;
  m_sizeBins.x = (m_sizeTiles.x + CR_BIN_SIZE - 1) >> CR_BIN_LOG2;
  m_sizeBins.y = (m_sizeTiles.y + CR_BIN_SIZE - 1) >> CR_BIN_LOG2;
  m_numBins = m_sizeBins.x * m_sizeBins.y;
}

void RasterImpl::swapDepthAndPeel(void) {
  m_peelBuffer.reset(
      m_depthBuffer.getSize()); // Ensure equal size and valid pointer.

  void *tmp = m_depthBuffer.getPtr();
  m_depthBuffer.setPtr(m_peelBuffer.getPtr());
  m_peelBuffer.setPtr(tmp);
}

//------------------------------------------------------------------------

bool RasterImpl::drawTriangles(const Vec2i *ranges, bool peel,
                               hipStream_t stream) {
  bool instanceMode = (!ranges);

  int maxSubtrisSlack = 4096;  // x 81B    = 324KB
  int maxBinSegsSlack = 256;   // x 2137B  = 534KB
  int maxTileSegsSlack = 4096; // x 136B   = 544KB

  // Resize atomics as needed.
  m_crAtomics.grow(m_numImages * sizeof(CRAtomics));
  m_crAtomicsHost.grow(m_numImages * sizeof(CRAtomics));

  // Size of these buffers doesn't depend on input.
  m_binFirstSeg.grow(m_numImages * CR_MAXBINS_SQR * CR_BIN_STREAMS_SIZE *
                     sizeof(S32));
  m_binTotal.grow(m_numImages * CR_MAXBINS_SQR * CR_BIN_STREAMS_SIZE *
                  sizeof(S32));
  m_activeTiles.grow(m_numImages * CR_MAXTILES_SQR * sizeof(S32));
  m_tileFirstSeg.grow(m_numImages * CR_MAXTILES_SQR * sizeof(S32));

  // Construct per-image parameters and determine worst-case buffer sizes.
  m_crImageParamsHost.grow(m_numImages * sizeof(CRImageParams));
  CRImageParams *imageParams = (CRImageParams *)m_crImageParamsHost.getPtr();
  for (int i = 0; i < m_numImages; i++) {
    CRImageParams &ip = imageParams[i];

    int roundSize = CR_BIN_WARPS * 32;
    int minBatches = CR_BIN_STREAMS_SIZE * 2;
    int maxRounds = 32;

    ip.triOffset = instanceMode ? 0 : ranges[i].x;
    ip.triCount = instanceMode ? m_numTriangles : ranges[i].y;
    ip.binBatchSize =
        min(max(ip.triCount / (roundSize * minBatches), 1), maxRounds) *
        roundSize;

    m_maxSubtris = max(m_maxSubtris,
                       min(ip.triCount + maxSubtrisSlack, CR_MAXSUBTRIS_SIZE));
    m_maxBinSegs =
        max(m_maxBinSegs, max(m_numBins * CR_BIN_STREAMS_SIZE,
                              (ip.triCount - 1) / CR_BIN_SEG_SIZE + 1) +
                              maxBinSegsSlack);
    m_maxTileSegs =
        max(m_maxTileSegs,
            max(m_numTiles, (ip.triCount - 1) / CR_TILE_SEG_SIZE + 1) +
                maxTileSegsSlack);
  }

  // Retry until successful.

  for (;;) {
    // Allocate buffers.
    m_triSubtris.reset(m_numImages * m_maxSubtris * sizeof(U8));
    m_triHeader.reset(m_numImages * m_maxSubtris * sizeof(CRTriangleHeader));
    m_triData.reset(m_numImages * m_maxSubtris * sizeof(CRTriangleData));

    m_binSegData.reset(m_numImages * m_maxBinSegs * CR_BIN_SEG_SIZE *
                       sizeof(S32));
    m_binSegNext.reset(m_numImages * m_maxBinSegs * sizeof(S32));
    m_binSegCount.reset(m_numImages * m_maxBinSegs * sizeof(S32));

    m_tileSegData.reset(m_numImages * m_maxTileSegs * CR_TILE_SEG_SIZE *
                        sizeof(S32));
    m_tileSegNext.reset(m_numImages * m_maxTileSegs * sizeof(S32));
    m_tileSegCount.reset(m_numImages * m_maxTileSegs * sizeof(S32));

    // AMD RDNA3: warpEmitMask + warpEmitPrefixSum live in global memory, one
    // CoarseGlobalScratch slot per (image, coarse-block).
    int numCoarseBlocks = m_numSMs * m_numCoarseBlocksPerSM;
    m_warpEmitGlobal.reset(m_numImages * numCoarseBlocks *
                           sizeof(CR::CoarseGlobalScratch));

    // Diagnostic trace buffer: 64 S32 slots in host-pinned memory. Kernel
    // writes go directly via PCIe so they survive a GPU fault. Zero-init.
    m_debugTrace.grow(64 * sizeof(S32));
    memset(m_debugTrace.getPtr(), 0, 64 * sizeof(S32));

    // Report if buffers grow from last time.
    size_t sizesTotal = getTotalBufferSizes();
    if (sizesTotal > m_bufferSizesReported) {
      size_t sizesMB = ((sizesTotal - 1) >> 20) + 1; // Round up.
      sizesMB = ((sizesMB + 9) / 10) *
                10; // 10MB granularity enough in this day and age.
      LOG(INFO) << "Internal buffers grown to " << sizesMB << " MB";
      m_bufferSizesReported = sizesMB << 20;
    }

    // AMD RDNA3 workaround: split into two launchStages calls (max 2 dispatches each).
    // 3+ kernel dispatches per call crashes on RDNA3/ROCm. Test 38 showed 2 dispatches
    // per call is stable across 120+ frames. The full host-side round-trip between calls
    // resets whatever runtime state triggers the crash.
    if (!peel) {
      launchStages(instanceMode, false, stream, 0); // triSetup + binRaster
      launchStages(instanceMode, false, stream, 1); // coarseRaster + fineRaster
    } else {
      launchStages(instanceMode, true, stream, 2);  // fineRaster only (peel)
    }

    // Peeling iteration cannot fail, so no point checking things further.
    if (peel)
      break;

    // Atomics after coarse stage are now available.
    CRAtomics *atomics = (CRAtomics *)m_crAtomicsHost.getPtr();

    // Diagnostic: log atomics on first few draws per instance, and always when zero output.
    m_drawCount++;
    for (int i = 0; i < m_numImages; i++) {
      const CRAtomics &a = atomics[i];
      if (m_drawCount <= 3 || a.numActiveTiles == 0) {
        std::cerr << "[drawTriangles @" << (void*)this
                  << " #" << m_drawCount << " img" << i << "] "
                  << "subtris=" << a.numSubtris
                  << " binSegs=" << a.numBinSegs
                  << " tileSegs=" << a.numTileSegs
                  << " activeTiles=" << a.numActiveTiles
                  << " tris=" << m_numTriangles
                  << " vp=" << m_sizeVp.x << "x" << m_sizeVp.y
                  << " tiles=" << m_numTiles
                  << " bins=" << m_numBins
                  << std::endl;
      }
    }

    // Success?
    bool failed = false;
    for (int i = 0; i < m_numImages; i++) {
      const CRAtomics &a = atomics[i];
      failed = failed || (a.numSubtris > m_maxSubtris) ||
               (a.numBinSegs > m_maxBinSegs) || (a.numTileSegs > m_maxTileSegs);
    }
    if (!failed)
      break; // Success!

    // If we were already at maximum capacity, no can do.
    if (m_maxSubtris == CR_MAXSUBTRIS_SIZE)
      return false;

    // Enlarge buffers and try again.
    for (int i = 0; i < m_numImages; i++) {
      const CRAtomics &a = atomics[i];
      m_maxSubtris = max(m_maxSubtris, min(a.numSubtris + maxSubtrisSlack,
                                           CR_MAXSUBTRIS_SIZE));
      m_maxBinSegs = max(m_maxBinSegs, a.numBinSegs + maxBinSegsSlack);
      m_maxTileSegs = max(m_maxTileSegs, a.numTileSegs + maxTileSegsSlack);
    }
  }

  m_deferredClear = false;
  return true; // Success.
}

//------------------------------------------------------------------------

size_t RasterImpl::getTotalBufferSizes(void) const {
  return m_colorBuffer.getSize() +
         m_depthBuffer.getSize() + // Don't include atomics and image params.
         m_triSubtris.getSize() + m_triHeader.getSize() + m_triData.getSize() +
         m_binFirstSeg.getSize() + m_binTotal.getSize() +
         m_binSegData.getSize() + m_binSegNext.getSize() +
         m_binSegCount.getSize() + m_activeTiles.getSize() +
         m_tileFirstSeg.getSize() + m_tileSegData.getSize() +
         m_tileSegNext.getSize() + m_tileSegCount.getSize() +
         m_warpEmitGlobal.getSize();
}

//------------------------------------------------------------------------

// stageSet: 0 = setup (triSetup + binRaster), 1 = raster (coarseRaster + fineRaster), 2 = peel (fineRaster only)
// AMD RDNA3 workaround: max 2 dispatches per call. drawTriangles calls this twice for non-peel.
void RasterImpl::launchStages(bool instanceMode, bool peel,
                              hipStream_t stream, int stageSet) {
  CRImageParams *imageParams = (CRImageParams *)m_crImageParamsHost.getPtr();

  // Atomics init only on stageSet 0 (first call of the pair).
  CRAtomics *atomics = (CRAtomics *)m_crAtomicsHost.getPtr();
  if (stageSet == 0) {
    memset(atomics, 0, m_numImages * sizeof(CRAtomics));
    for (int i = 0; i < m_numImages; i++)
      atomics[i].numSubtris = imageParams[i].triCount;
    NVDR_CHECK_CUDA_ERROR(hipMemcpyAsync(m_crAtomics.getPtr(), atomics,
                                         m_numImages * sizeof(CRAtomics),
                                         hipMemcpyHostToDevice, stream));
  } else if (stageSet == 2) {
    // Peel: upload atomics without reinit.
    NVDR_CHECK_CUDA_ERROR(hipMemcpyAsync(m_crAtomics.getPtr(), atomics,
                                         m_numImages * sizeof(CRAtomics),
                                         hipMemcpyHostToDevice, stream));
  }

  // Build CRParams and upload to device.
  CRParams p;
  {
    p.atomics = (CRAtomics *)m_crAtomics.getPtr();
    p.numImages = m_numImages;
    p.totalCount = 0;
    p.instanceMode = instanceMode ? 1 : 0;
    p.numVertices = m_numVertices;
    p.numTriangles = m_numTriangles;
    p.vertexBuffer = m_vertexPtr;
    p.indexBuffer = m_indexPtr;
    p.widthPixels = m_sizePixels.x;
    p.heightPixels = m_sizePixels.y;
    p.widthPixelsVp = m_sizeVp.x;
    p.heightPixelsVp = m_sizeVp.y;
    p.widthBins = m_sizeBins.x;
    p.heightBins = m_sizeBins.y;
    p.numBins = m_numBins;
    p.xs = (float)m_bufferSizeVp.x / (float)m_sizeVp.x;
    p.ys = (float)m_bufferSizeVp.y / (float)m_sizeVp.y;
    p.xo = (float)(m_bufferSizeVp.x - m_sizeVp.x - 2 * m_offsetPixels.x) /
           (float)m_sizeVp.x;
    p.yo = (float)(m_bufferSizeVp.y - m_sizeVp.y - 2 * m_offsetPixels.y) /
           (float)m_sizeVp.y;
    p.widthTiles = m_sizeTiles.x;
    p.heightTiles = m_sizeTiles.y;
    p.numTiles = m_numTiles;
    p.renderModeFlags = m_renderModeFlags;
    p.deferredClear = m_deferredClear ? 1 : 0;
    p.clearColor = m_clearColor;
    p.clearDepth = CR_DEPTH_MAX;
    p.maxSubtris = m_maxSubtris;
    p.maxBinSegs = m_maxBinSegs;
    p.maxTileSegs = m_maxTileSegs;
    p.triSubtris = m_triSubtris.getPtr();
    p.triHeader = m_triHeader.getPtr();
    p.triData = m_triData.getPtr();
    p.binSegData = m_binSegData.getPtr();
    p.binSegNext = m_binSegNext.getPtr();
    p.binSegCount = m_binSegCount.getPtr();
    p.binFirstSeg = m_binFirstSeg.getPtr();
    p.binTotal = m_binTotal.getPtr();
    p.tileSegData = m_tileSegData.getPtr();
    p.tileSegNext = m_tileSegNext.getPtr();
    p.tileSegCount = m_tileSegCount.getPtr();
    p.activeTiles = m_activeTiles.getPtr();
    p.tileFirstSeg = m_tileFirstSeg.getPtr();
    p.warpEmitGlobal = m_warpEmitGlobal.getPtr();
    p.debugTrace = m_debugTrace.getPtr();
    // Reset diagnostic trace at start of each draw. Init slot 9 to
    // UINT32_MAX so atomicMin works correctly. Slots 0..8, 10+ = 0.
    {
      uint32_t* dbgU = (uint32_t*)m_debugTrace.getPtr();
      memset(dbgU, 0, 64 * sizeof(uint32_t));
      dbgU[9] = 0xFFFFFFFFu;
    }
    size_t byteOffset =
        ((size_t)m_offsetPixels.x +
         (size_t)m_offsetPixels.y * (size_t)m_bufferSizePixels.x) *
        sizeof(U32);
    p.colorBuffer = m_colorBuffer.getPtr(byteOffset);
    p.depthBuffer = m_depthBuffer.getPtr(byteOffset);
    p.peelBuffer =
        (m_renderModeFlags & CudaRaster::RenderModeFlag_EnableDepthPeeling)
            ? m_peelBuffer.getPtr(byteOffset)
            : 0;
    p.strideX = m_bufferSizePixels.x;
    p.strideY = m_bufferSizePixels.y;
    memcpy(&p.imageParamsFirst, imageParams,
           min(m_numImages, CR_EMBED_IMAGE_PARAMS) * sizeof(CRImageParams));
    p.imageParamsExtra = (CRImageParams *)m_crImageParamsExtra.getPtr();
  }

  CRParams* d_crParams = (CRParams*)m_d_crParams;
  if (!d_crParams) {
    NVDR_CHECK_CUDA_ERROR(hipMalloc(&d_crParams, sizeof(CRParams)));
    m_d_crParams = d_crParams;
  }
  NVDR_CHECK_CUDA_ERROR(hipMemcpyAsync(d_crParams, &p, sizeof(CRParams),
                                       hipMemcpyHostToDevice, stream));

  if (stageSet == 0) {
    // Setup batch: triSetup + binRaster (2 dispatches).
    int stage0 = 0;
    void *argsS0[] = {&d_crParams, &stage0};
    NVDR_CHECK_CUDA_ERROR(hipLaunchKernel(
        (void *)setupKernel,
        dim3((m_numTriangles - 1) / (CR_SETUP_WARPS * 32) + 1, 1, m_numImages),
        dim3(32, CR_SETUP_WARPS), argsS0, 0, stream));

    int stage1 = 1;
    void *argsS1[] = {&d_crParams, &stage1};
    NVDR_CHECK_CUDA_ERROR(hipLaunchKernel(
        (void *)setupKernel, dim3(CR_BIN_STREAMS_SIZE, 1, m_numImages),
        dim3(32, CR_BIN_WARPS), argsS1, 0, stream));

  } else if (stageSet == 1) {
    // Raster batch: coarseRaster + fineRaster (2 dispatches of rasterKernel).
    // Static shared memory in kernel -- no dynamic smem needed (0 bytes).
    int stage0 = 0;
    void *argsR0[] = {&d_crParams, &stage0};
    NVDR_CHECK_CUDA_ERROR(hipLaunchKernel(
        (void *)rasterKernel,
        dim3(m_numSMs * m_numCoarseBlocksPerSM, 1, m_numImages),
        dim3(32, CR_COARSE_WARPS), argsR0, 0, stream));

    // Test 122: skip fine launch entirely. If coarse alone passes,
    // fault is somehow from fine. If still crashes, fault is in coarse.
#if 0
    int stage1 = 1;
    void *argsR1[] = {&d_crParams, &stage1};
    NVDR_CHECK_CUDA_ERROR(hipLaunchKernel(
        (void *)rasterKernel,
        dim3(m_numSMs * m_numFineBlocksPerSM, 1, m_numImages),
        dim3(32, m_numFineWarpsPerBlock), argsR1, 0, stream));
#endif

  } else {
    // Peel: fineRaster only (1 dispatch). Static smem, 0 dynamic.
    int stage1 = 1;
    void *argsR1[] = {&d_crParams, &stage1};
    NVDR_CHECK_CUDA_ERROR(hipLaunchKernel(
        (void *)rasterKernel,
        dim3(m_numSMs * m_numFineBlocksPerSM, 1, m_numImages),
        dim3(32, m_numFineWarpsPerBlock), argsR1, 0, stream));
  }

  // Copy atomics back after raster batch (stageSet 1) for overflow detection.
  if (stageSet == 1) {
    NVDR_CHECK_CUDA_ERROR(hipMemcpyAsync(
        m_crAtomicsHost.getPtr(), m_crAtomics.getPtr(),
        sizeof(CRAtomics) * m_numImages, hipMemcpyDeviceToHost, stream));
  }

  // Print diagnostic trace BEFORE sync. Host-pinned memory means kernel writes
  // are visible via PCIe immediately. If sync triggers SIGABRT from a GPU fault,
  // we still got the trace.
  if (stageSet == 1) {
    S32* trace = (S32*)m_debugTrace.getPtr();
    if (trace) {
      // Brief poll: give the kernel a moment to make progress / fault.
      for (int i = 0; i < 50; i++) {
        if (trace[0] > 0) break;
        usleep(10000); // 10ms x 50 = up to 500ms
      }
      std::cerr << "[trace] coarseRaster deepest checkpoint = " << trace[0] << std::endl;
      // Test 115+ diagnostic dump. Slots 1..7 hold the values written by
      // the kernel's per-warp atomicCAS-protected diagnostic block. See
      // CoarseRaster.inl line ~360.
      // Always print slot 12-14 if any of them is set (Test 123+ triIdx diag)
      if (trace[12] || trace[13] || trace[14] || trace[16] || trace[17]) {
        uint32_t triIdx = (uint32_t)trace[12];
        uint32_t dataIdx = (uint32_t)trace[13];
        uint32_t maxSubtris = (uint32_t)trace[14];
        uint32_t preCnt = (uint32_t)trace[16];
        uint32_t postCnt = (uint32_t)trace[17];
        std::cerr << "[diag-tri] sample triIdx=" << triIdx
                  << " dataIdx=" << dataIdx
                  << " maxSubtris=" << maxSubtris
                  << std::endl;
        std::cerr << "[diag-OOB-counts] pre-misc OOB threads=" << preCnt
                  << " post-misc OOB threads=" << postCnt
                  << std::endl;
        if (trace[18]) {
          std::cerr << "[diag-preOOB-sample] triIdx=" << (uint32_t)trace[19]
                    << " origDataIdx=" << (uint32_t)trace[20]
                    << " threadIdx=(" << ((trace[21] >> 16) & 0xffff)
                    << "," << (trace[21] & 0xffff) << ")"
                    << std::endl;
        }
        if (trace[22]) {
          std::cerr << "[diag-postOOB-sample] triIdx=" << (uint32_t)trace[23]
                    << " origDataIdx=" << (uint32_t)trace[24]
                    << " subtriIdx=" << (uint32_t)trace[25]
                    << " final_dataIdx=" << (int32_t)trace[26]
                    << " misc=" << (uint32_t)trace[27]
                    << std::endl;
        }
      }
      if (trace[1]) {
        uint64_t offset = ((uint64_t)(uint32_t)trace[3] << 32) | (uint32_t)trace[2];
        std::cerr << "[diag-sample] currPtr_offset=" << offset
                  << " threadIdx=(" << ((trace[4] >> 16) & 0xffff) << "," << (trace[4] & 0xffff) << ")"
                  << " lox=" << ((trace[5] >> 16) & 0xffff) << " loy=" << (trace[5] & 0xffff)
                  << " blockIdx=(" << ((trace[6] >> 16) & 0xffff) << ",_," << (trace[6] & 0xffff) << ")"
                  << std::endl;
      }
      std::cerr.flush();
    }
  }
  NVDR_CHECK_CUDA_ERROR(hipStreamSynchronize(stream));
}

//------------------------------------------------------------------------
